### ISSUE TITLE
[feature/controller] MenuController, LifeController 만들기

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#1]
# 1. TODO
- [x] Action 만들기(`Grid `는 worker 개발 시 구현)
  - `Go`: `Clear`, `Load`, `Store`, `Exit`
  - `Grid`: `Halt`, `Tick (Single Step)`, `Agonizing`, `Slow`, `Medium`, `Fast`
  - `Life`: `Component`, `Life`
- [x] MenuBar에 menu 넘겨주는 기능 만들기
- [x] `mouseListener` action 만들기
- [x] `componentListener` action 만들기
- [x] `LifeController`에서 `LifePanel`에 action 등록하는 기능 만들기

---

# 2. Test Case
- [x] MenuBar에 잘 넘겨주는지 테스트
- [x] LifePanel에 잘 넘겨주는지 테스트
- [x] action에서 알맞는 메서드를 잘 호출하는지 혹은 잘 기능하는지 테스트
  - `Go`: `Clear`, `Load`, `Store`, `Exit`
  - Life: `Component`, `Life`

---

# 3. 유의사항
- Issue #13 
- `com.LifeGame.controller`에서 작업
- [MVC+Observer 패턴 참고자료](https://velog.io/@te-ing/자바스크립트-디자인패턴)
- [Swing+MVC 패턴 예제 참고자료](https://dev4-me.tistory.com/entry/MVC-패턴을-사용하여-Java-SWING으로-계산기-프로그램-만들기)

**Comment by AllyHyeseongKim** [comment]
1. 문제제기: `controller`가 `view`에 의존하고 있다. 

https://github.com/CAU-DesignPattern/LifeGame/blob/29add00ca2580480135e0eafabdc4cd8d1446985/src/main/java/com/LifeGame/controller/action/ClearAction.java#L14-L15
https://github.com/CAU-DesignPattern/LifeGame/blob/29add00ca2580480135e0eafabdc4cd8d1446985/src/main/java/com/LifeGame/controller/action/ComponentAction.java#L13
https://github.com/CAU-DesignPattern/LifeGame/blob/29add00ca2580480135e0eafabdc4cd8d1446985/src/main/java/com/LifeGame/controller/action/LifeAction.java#L13
https://github.com/CAU-DesignPattern/LifeGame/blob/29add00ca2580480135e0eafabdc4cd8d1446985/src/main/java/com/LifeGame/controller/action/LoadAction.java#L18
  - `view`에 변화가 있을 경우 `view`를 가지는 `controller`를 다 찾아서 수정해야 한다. `OCP 위배`
2. 문제제기: menu의 순서가 지켜지지 않는다.
- menu의 순서를 어디선가 담아야 한다. `view` vs `controller`
- `controller`는 `view`의 요청에 따라 `model`을 수정하는 역할을 하는 것이므로 `menu`의 순서는 `view`가 담고 있어야 한다. 
- layer 구조: `view`-`controller`-`service`-`model`
  - `view`-`controller`-`model`(`service`+`entity`)
