### ISSUE TITLE
[feature/worker] thread

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#10]
# 1. TODO
- [x] `thread`를 사용하여 `nextState`를 계산하는 기능 만들기
- [x] `Halt` 기능 만들기
- [x] 속도 조절하는 기능 만들기
  - `Agonizing,` `Slow`, `Medium`, `Fast` 

---

# 2. Test Case
- [x] worker가 잘 기능하는지 테스트
- [x] action이 잘 기능하는지 테스트
  - `Halt`, `Agonizing,` `Slow`, `Medium`, `Fast` 

---

# 3. 유의사항
- 스레드를 사용하여 View를 업데이트 할 시 동시성 문제 발생 예상: `synchronized` 사용
