### ISSUE TITLE
[feature/view] ActionListener 만들기

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#11]
# 0. Introduction
1. 문제제기: Issue #8 
- `ActionListener`를 `controller`에 달고자 했더니 다음 두 개의 문제가 있다.
  - action을 if문으로 받을 경우, 분기가 많아 메뉴 확장 시 `controller`를 뜯어고쳐야 하는 경우가 발생할 수 있다. `OCP 위배`
  - 각 action을 다 분리할 경우, class가 너무 많아진다.
- `ActionListener`를 `controller`에 달면 `controller`의 `view`에 대한 의존성이 심해진다.
  - `controller`는 `view`가 수정되더라도 수정없이 제 역할을 할 수 있어야 한다. `OCP`
  - ex. `SWING`으로 된 `view`를 `JavaFX`로 바꾸고자 할 때, `controller`를 수정해야 한다. `OCP 위배`
  - `view`에서 `ActionListener`로 action을 읽고 `ApplicationContext`에 있는 `controller` `bean`을 가져와서 `controller`에 있는 해당 action의 메소드를 호출해야 한다.(`view`가 `controller`를 알고 있으면 안되므로 @Autowired로 처음부터 `controller`를 가지고 있으면 안된다.)
  - ex. 웹에서는 프론트 단에서 action을 읽고 처리를 넘긴다.

---

# 1. TODO
- [x] `Grid` menu의 `ActionListener` 만들기
  - `Clear`, `Load`, `Store`, `Exit`
- [x] `Go` menu의 `ActionListener` 만들기
  - `Halt`, `Tick (Single Step)`, `Agonizing`, `Slow`, `Medium`, `Fast`

---

# 2. Test Case
- [x] `Grid` menu에서 `controller`의 메소드를 잘 호출하는지 테스트
- [x] `Go` menu에서 `controller`의 메소드를 잘 호출하는지 테스트

---

# 3. 유의사항
- [Java and GUI - Where do ActionListeners belong according to MVC pattern?](https://stackoverflow.com/questions/26517856/java-and-gui-where-do-actionlisteners-belong-according-to-mvc-pattern)

**Comment by AllyHyeseongKim** [comment]
`View`에 등록하는 메뉴가 바뀌면, `ActionListener`로 호출할 부분을 연결하는 것도 변경해야 한다. 이를 한 곳으로 통일할 수 없을까?
- 메뉴들은 데이터라고 볼 수 있다. > `model`로 들어가야 한다.
- 메뉴에 대한 정보를 `model`에 넣고 `view`가 menu 정보를 `controller`에 요청하면 `controller`가 `model`에서 메뉴 정보를 가져와서 전달하고 이를 바탕으로 `view`가 그릴 수 있게 해야 한다.

**Comment by AllyHyeseongKim** [comment]
Move to Issue #13

**Comment by AllyHyeseongKim** [comment]
Move to Issue #13
