### ISSUE TITLE
[feature/model] Map size 설정 및 dot update 

### ISSUE THREAD

**Issue by maxCM** [CAU-DesignPattern/LifeGame#15]
# 1. TODO
- [x]  Map Size 설정
  - `배열` 사용(ex. `ArrayList` 등)
- [x] dot update
  - click된 곳 배열에서 변화시키기

---

# 2. Test Case
- [x]  설정한 값이 배열로 저장되는지 테스트
- [x]  click(입력값)에 대한 변화가 있는지 테스트
- [x] set - toggle - next state 연결해서 테스트

---

# 3. 유의사항
- `com.LifeGame.model`에서 작업
