### ISSUE TITLE
[feature/controller] view-controller 리팩토링

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#19]
# 0. Introduction
1. 문제제기: https://github.com/CAU-DesignPattern/LifeGame/issues/1#issuecomment-1326750480
- layer 구성
  - `view`: `View`, `MenuBar`, `LifePanel`
  - `controller`: `ViewController`, `MenuController`, `LifeController`
  - `service`: `FileService`
    - `model`: `MenuModel`, `LifeModel`
- `view`에서 menu를 순서대로 `model`에 저장하도록 `ViewController`에게 요청한다.
  - 이때, `actionListener`는 `MenuController`에 있는 메소드를 넘긴다.
  - `actionListener`는 `command 패턴`을 이용하여 구성한다.
- `ViewController`는 해당 menu들을 `model`에 저장한다.
- `model`을 `notify`하고 있는 menuBar는 업데이트된 menu 정보를 `notify` 받아 등록한다.

---

# 1. TODO
- [x] action의 menu 등록을 `View`로 옮기기
- [x] action을 `MenuController`, `LifeController`로 합치기
- [x] `MenuModel` 만들기
- [x] `view`와 `model`을 `observer pattern`으로 연결하기

---

# 2. Test Case
- _해당사항 없음_

---

# 3. 유의사항
- [MVC 패턴 구현](https://velog.io/@ljina0218/MVC-패턴-구현)
