### ISSUE TITLE
[feature/model] Life state를 업데이트하는 기능 만들기

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#2]
# 1. TODO
- [x] 현재 Life state에서 다음 Life state로 바꾸는 기능 만들기
  - `배열` 사용(ex. `ArrayList` 등)
  - 설정에 따라 `배열`의 크기를 바꿀 수 있게 만들 수 있어야 함
  - **시간 복잡도**를 최소로 만들 수 있는 로직

---

# 2. Test Case
- [x] 3x3 `배열`에 대하여 3개의 각 패턴이 잘 적용되는지 테스트
- [x] 벽에서의 다음 Life state가 정확하게 계산되는지 테스트

---

# 3. 유의사항
- `com.LifeGame.model`에서 작업
- **최소 시간복잡도**로 만들기
