### ISSUE TITLE
[feature/view] observer 패턴으로 view 업데이트하는 기능 만들기

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#28]
# 1. TODO
- [x] view와 model에 Observer pattern 적용하기
- [x] action 수정하기: Load, Store, Tick

---

# 2. Test Case
- [x] 테스트 수정
- [x] mapChanged 호출 시 LifePanel에서 update가 잘 호출되는지 테스트

---

# 3. 유의사항
- _해당사항 없음_
