### ISSUE TITLE
[feature/model] nextState 수정

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#29]
# 0. Introduction
https://github.com/CAU-DesignPattern/LifeGame/blob/7bd360bf24a3e3b7e949bf91b21dd33da78bc845/src/main/java/com/LifeGame/model/Model.java#L42-L71

---
# 1. TODO
- [x] nextState를 this.model의 다음 단계를 계산하도록 수정하기
  - parameter -> 삭제
  - 메서드 내부: this.model 사용
 
---
# 2. Test Case
- [x] 기존 테스트 수정
- [x] mapChanged가 잘 호출되는지 테스트
