### ISSUE TITLE
[feature/service] 현재 state를 저장하는 기능 만들기

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#3]
# 1. TODO
- [x] load action 실패 시 에러 alert
- [x] store 구현 - 파라미터로 받은 MapData 객체를 JSON 파일로 저장하기
- [x] load 구현 - JSON 파일을 다시 MapData 객체로 변환하여 불러오기

---

# 2. Test Case
- [x] Load Action Test : Alert 테스트 추가 - UI 분리 필요
- [x] Store 테스트 
- [x] Load 테스트

---

# 3. 유의사항
- `com.LifeGame.service`에서 작업
- [메멘토 패턴 예제 참고자료](https://blog.naver.com/seek316/222108653677)
