### ISSUE TITLE
[feature/model] 현재 세대와 살아있는 셀의 수 계산

### ISSUE THREAD

**Issue by maxCM** [CAU-DesignPattern/LifeGame#36]
# 1. TODO
- [x]  현재 세대 수 계산
- [x]  살아있는 셀 수 계산

---

# 2. Test Case
- [x]  next state시 generation이 증가하는지 확인
- [x]  clearmap하면 generation이 0으로 초기화되어야함
- [x]  현재 살아있는 세포의 수 계산 (next state & toggle할 때마다 update)
- [x]  clearmap하면 livecell이 0으로 초기화되어야함

---

# 3. 유의사항
- `com.LifeGame.model`에서 작업
