### ISSUE TITLE
[develop] Swing + Spring Boot Application 초기화 및 Interface 선언

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#4]
# 1. TODO
- [x] Spring Boot Application main method 설정
  - `new SpringApplicationBuilder(Application.class).headless(false).web(WebApplicationType.NONE).run(args);`
- [x] Spring Boot CommandLineRunner를 구현하여 view 가져오기
  - `org.springframework.boot.CommandLineRunner`
- [x] view(구현체) 예시 만들기
  - Observer
  - `JFrame`
- [x] model(인터페이스, 구현체) 예시 만들기
  - Observable
  - nextState, setMapSize, toggle
- [x] controller(인터페이스, 구현체) 예시 만들기
- [x] service(인터페이스, 구현체) 예시 만들기

---

# 2. Test Case
- _해당사항 없음_
---

# 3. 유의사항
- [Spring Boot+Swing 참고자료](https://github.com/mightychip/spring-boot-swing/tree/master/src/main/java/ca/purpleowl/examples/swing)
- [Spring Boot 구동 시 특정 코드 실행 참고자료](https://www.daleseo.com/spring-boot-runners/)
