### ISSUE TITLE
[feature/view] 현재 상태 view에 update

### ISSUE THREAD

**Issue by maxCM** [CAU-DesignPattern/LifeGame#40]
# 1. TODO
- [ ]  status panel 만들기
- [ ]  livecell을 패널에 업데이트
- [ ]  generation을 패널에 업데이트

---

# 2. Test Case
- [ ]  
- [ ]  
- [ ]  

---

# 3. 유의사항
-
