### ISSUE TITLE
[feature/view] menu bar 리팩토링

### ISSUE THREAD

**Issue by AllyHyeseongKim** [CAU-DesignPattern/LifeGame#8]
# 0. Introduction
1. 문제 제기: Issue #6, PR #7
https://github.com/CAU-DesignPattern/LifeGame/blob/c59dcee050c1977031273f32dd7eb00809d9c1fe/src/main/java/com/LifeGame/view/View.java#L42-L94
  - 모든 menu item을 View 인스턴스가 만들면 메뉴를 확장하고자 했을 때 수정해야 한다.(`Go` menu에서 속도를 더 다양하게 설정하고 싶음) `OCP 위배`
    - 원본 코드처럼 메뉴 생성을 View 인스턴스로부터 분리해야 한다.
  - `MVC`를 분리하기 위해 `controller`에서 `ActionListener`를 주입하려 했더니 MenuView를 수정해야 한다. `OCP 위배`
    - MenuView에서 `ActionListener`를 설정하는 것을 없애야 한다.
2. 문제 제기: Issue #6, PR #7
https://github.com/CAU-DesignPattern/LifeGame/blob/c59dcee050c1977031273f32dd7eb00809d9c1fe/src/main/java/com/LifeGame/view/MenuView.java#L99-L444
  - `static` field가 너무 많다.
    - `static` field의 문제점: 이해가 어려워 Test를 작성하는 것이 어렵다.
    - MenuView에서 `static`이 들어가는 부분을 `Spring Bean`을 이용하여 수정한다.

---

# 1. TODO
- [x] `com.LifeGame.view.MenuView`를 수정하여 메뉴와 메뉴 아이템을 새로 추가하는 기능 만들기
- [x] `com.LifeGame.view.View`의 `initMenu()`에서 `Grid` menu, `Go` menu 생성 분리
  - Grid: Clear, Load, Store, Exit
  - Go: Halt, Tick (Single Step), Slow, Medium, Fast

---

# 2. Test Case
- [x] menu가 잘 생성되는지 테스트
- [x] menu가 잘 삭제되는지 테스트
- [x] menu 이름이 잘 수정되는지 테스트
- [x] menu가 잘 반환되는지 테스트
- [x] menuItem이 잘 생성되는지 테스트
- [x] menuItem이 잘 삭제되는지 테스트
- [x] menuitem 이름이 잘 수정되는지 테스트
- [x] menuitem이 잘 반환되는지 테스트

---

# 3. 유의사항
- `com.LifeGame.view`에서 작업
- [MVC구조가 생겨난 계기](https://okky.kr/articles/453210)
- [왜 자바에서 static의 사용을 지양해야 하는가?](https://unabated.tistory.com/1041)

**Comment by AllyHyeseongKim** [comment]
ActionListener는 Controller에 있어야 하는게 맞나?
[Java and GUI - Where do ActionListeners belong according to MVC pattern?](https://stackoverflow.com/questions/26517856/java-and-gui-where-do-actionlisteners-belong-according-to-mvc-pattern)
